backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

logo:
  src: "/images/logo.webp"
  show_in_header: true

display_url: "https://umthombho.netlify.app"
site_url: "https://umthombho.netlify.app"

locale: "en"

i18n:
  structure: multiple_folders
  locales: ["en", "xh"]
  default_locale: "en"

slug:
  encoding: "unicode"

roles:
  - label: "Admin"
    name: "admin"
  - label: "Editor"
    name: "editor"
  - label: "Author"
    name: "author"
  - label: "Contributor"
    name: "contributor"

collections:
  - name: "journal"
    label: "Journal"
    label_singular: "Journal Entry"
    folder: "content/journal"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    i18n: true  # inherits from top-level config
    fields:
      - {label: "Language", name: "language", widget: "select", options: [{label: "English", value: "en"}, {label: "isiXhosa", value: "xh"}], default: "en"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Featured Image", name: "image", widget: "image", required: false}
    editor:
      preview: true
